"""scripts/offline/build_release.py 纯函数单元测试 (不联网)。

覆盖: uv.lock 闭包解析、requirements 解析、test 依赖集合、
wheelhouse 完整性校验 (sdist 检测 / unresolved 检测)、runtime 版本定义。
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

import build_release as br
import release_manifest as rm

REPO_ROOT = Path(__file__).resolve().parent.parent


class TestLockClosures:
    def test_runtime_closure_from_uv_lock(self) -> None:
        runtime, _ = br.lock_closures()
        for name in (
            "click",
            "pydantic",
            "pydantic-core",
            "pymysql",
            "pyyaml",
            "requests",
            "zstandard",
            "tzdata",
            "certifi",
        ):
            assert name in runtime, name
        assert re.fullmatch(r"\d+\.\d+\.\d+", runtime["click"])
        assert "ruff" not in runtime and "pytest" not in runtime

    def test_dev_only_closure_contains_pytest_tree(self) -> None:
        _, dev_only = br.lock_closures()
        for name in ("pytest", "packaging", "pluggy", "iniconfig"):
            assert name in dev_only, name

    def test_test_requirements_exclude_ruff_and_runtime(self) -> None:
        runtime, dev_only = br.lock_closures()
        pins = br.test_requirements(runtime, dev_only)
        assert "ruff" not in pins
        assert "pytest" in pins
        assert all(name not in pins for name in runtime)


class TestRequirementParsing:
    def test_parses_pins_and_skips_comments(self) -> None:
        text = (
            "# autogenerated header\n"
            "click==8.5.0\n"
            "colorama==0.4.6; platform_system == 'Windows'\n"
            "\n"
            "--index-url https://example.invalid\n"
        )
        assert br.parse_requirement_pins(text) == {
            "click": "8.5.0",
            "colorama": "0.4.6",
        }

    def test_rejects_unpinned_line(self) -> None:
        with pytest.raises(br.BuildError, match="name==version"):
            br.parse_requirement_pins("click>=8.1\n")

    def test_normalize_name(self) -> None:
        assert br.normalize_name("Pydantic_Core") == "pydantic-core"
        assert br.normalize_name("typing-extensions") == "typing-extensions"


class TestWheelhouseValidation:
    def test_complete_wheelhouse(self, tmp_path: Path) -> None:
        (tmp_path / "click-8.5.0-py3-none-any.whl").write_bytes(b"x")
        (tmp_path / "pydantic_core-2.46.5-cp313-cp313-manylinux2014_x86_64.whl").write_bytes(b"x")
        wheels, unresolved, sdists = br.validate_wheelhouse(
            tmp_path, {"click": "8.5.0", "pydantic-core": "2.46.5"}
        )
        assert (wheels, unresolved, sdists) == (2, [], [])

    def test_sdist_rejected(self, tmp_path: Path) -> None:
        (tmp_path / "click-8.5.0-py3-none-any.whl").write_bytes(b"x")
        (tmp_path / "evil-1.0.tar.gz").write_bytes(b"x")
        _, _, sdists = br.validate_wheelhouse(tmp_path, {"click": "8.5.0"})
        assert sdists == ["evil-1.0.tar.gz"]

    def test_unresolved_dependency(self, tmp_path: Path) -> None:
        (tmp_path / "click-8.5.0-py3-none-any.whl").write_bytes(b"x")
        _, unresolved, _ = br.validate_wheelhouse(
            tmp_path, {"click": "8.5.0", "zstandard": "0.25.0"}
        )
        assert unresolved == ["zstandard"]

    def test_missing_directory(self, tmp_path: Path) -> None:
        wheels, unresolved, _ = br.validate_wheelhouse(tmp_path / "nope", {"click": "8.5.0"})
        assert wheels == 0 and unresolved == ["click"]


class TestRuntimeVersions:
    def load(self) -> dict:
        return json.loads((br.RUNTIME_VERSIONS_PATH).read_text(encoding="utf-8"))

    def test_python_version_is_pinned_xyz(self) -> None:
        assert re.fullmatch(r"\d+\.\d+\.\d+", self.load()["python"])

    def test_windows_uses_external_python_path(self) -> None:
        windows = self.load()["windows"]
        assert windows == {"runtime_policy": "external-python-path"}

    def test_linux_runtime_is_pbs_install_only_stripped(self) -> None:
        linux = self.load()["linux_x86_64"]
        assert "astral-sh/python-build-standalone/releases/download" in linux["url"]
        assert "x86_64-unknown-linux-gnu-install_only_stripped.tar.gz" in linux["artifact"]
        assert linux["url"].endswith(linux["artifact"])
        assert linux["sha256sums_url"].endswith("/SHA256SUMS")
        assert re.fullmatch(r"[0-9a-f]{64}", linux["sha256"])

    def test_versions_consistent_with_pinned_python(self) -> None:
        data = self.load()
        assert data["python"] in data["linux_x86_64"]["artifact"]


class TestPlatformSpecs:
    def test_linux_requires_glibc_2_17(self) -> None:
        assert br.PLATFORM_SPECS["linux"]["minimum_glibc"] == "2.17"
        assert br.PLATFORM_SPECS["windows"]["minimum_glibc"] is None
        assert "manylinux2014_x86_64" in br.PLATFORM_SPECS["linux"]["pip_platforms"]
        assert "win_amd64" in br.PLATFORM_SPECS["windows"]["pip_platforms"]


class TestBundleRuntimePolicy:
    @staticmethod
    def manifest(platform: str, runtime_artifact: str | None) -> rm.ReleaseManifest:
        return rm.ReleaseManifest(
            release_id="0.1.0-abcdef0",
            app_version="0.1.0",
            git_commit="abcdef0" + "1" * 33,
            created_at="2026-09-16T00:00:00+00:00",
            python_version="3.13.15",
            platform_os=platform,
            platform_arch="amd64" if platform == "windows" else "x86_64",
            minimum_glibc=None if platform == "windows" else "2.17",
            source_state_schema=4,
            destination_metadata_schema=3,
            runtime_policy=(
                rm.RUNTIME_POLICY_EXTERNAL_PYTHON_PATH
                if platform == "windows"
                else rm.RUNTIME_POLICY_BUNDLED
            ),
            runtime_artifact=runtime_artifact,
            app_wheel="airgap_sync-0.1.0-py3-none-any.whl",
            wheel_count=1,
            include_tests=False,
        )

    @staticmethod
    def inputs(tmp_path: Path) -> tuple[Path, Path]:
        app = tmp_path / "airgap_sync-0.1.0-py3-none-any.whl"
        app.write_bytes(b"app")
        wheelhouse = tmp_path / "wheels"
        wheelhouse.mkdir()
        (wheelhouse / "click-8.5.0-py3-none-any.whl").write_bytes(b"wheel")
        return app, wheelhouse

    def test_windows_bundle_has_no_runtime_payload(self, tmp_path: Path) -> None:
        app, wheelhouse = self.inputs(tmp_path)
        bundle = br.assemble_bundle(
            tmp_path / "build",
            "windows",
            self.manifest("windows", None),
            app,
            None,
            wheelhouse,
            None,
        )
        assert not (bundle / "runtime").exists()
        assert not list(bundle.rglob("python-*.exe"))
        assert not list(bundle.rglob("cpython-*.tar.gz"))

    def test_linux_bundle_keeps_pbs_runtime(self, tmp_path: Path) -> None:
        app, wheelhouse = self.inputs(tmp_path)
        runtime_name = "cpython-3.13.15+20260901-x86_64-unknown-linux-gnu-install_only.tar.gz"
        runtime = tmp_path / runtime_name
        runtime.write_bytes(b"runtime")
        bundle = br.assemble_bundle(
            tmp_path / "build",
            "linux",
            self.manifest("linux", runtime_name),
            app,
            runtime,
            wheelhouse,
            None,
        )
        assert (bundle / "runtime" / runtime_name).read_bytes() == b"runtime"

    def test_linux_download_platforms_reject_generic_linux_and_musl(self) -> None:
        """generic linux_x86_64 / musllinux 不提供 glibc <= 2.17 ABI 承诺。"""
        platforms = br.PLATFORM_SPECS["linux"]["pip_platforms"]
        assert "linux_x86_64" not in platforms
        assert not any(p.startswith("musllinux") for p in platforms)
        for allowed in ("manylinux2014_x86_64", "manylinux_2_17_x86_64"):
            assert allowed in platforms


class TestLinuxWheelAbiGuard:
    @pytest.mark.parametrize(
        ("wheel", "compatible"),
        [
            # universal wheels run anywhere
            ("foo-1.0-py3-none-any.whl", True),
            ("foo-1.0-py2.py3-none-any.whl", True),
            # CentOS 7 (glibc 2.17) compatible tags
            ("foo-1.0-cp313-cp313-manylinux_2_17_x86_64.whl", True),
            ("foo-1.0-cp313-cp313-manylinux2014_x86_64.whl", True),
            ("foo-1.0-cp313-cp313-manylinux_2_12_x86_64.whl", True),
            ("foo-1.0-cp313-cp313-manylinux2010_x86_64.whl", True),
            ("foo-1.0-cp313-cp313-manylinux1_x86_64.whl", True),
            ("foo-1.0-cp313-cp313-manylinux_2_5_x86_64.whl", True),
            # multi-tag wheel: one glibc <= 2.17 tag is enough
            (
                "foo-1.0-cp313-cp313-manylinux_2_28_x86_64.manylinux_2_17_x86_64.whl",
                True,
            ),
            # no ABI promise for glibc 2.17
            ("foo-1.0-cp313-cp313-linux_x86_64.whl", False),
            ("foo-1.0-cp313-cp313-manylinux_2_28_x86_64.whl", False),
            ("foo-1.0-cp313-cp313-manylinux_2_18_x86_64.whl", False),
            ("foo-1.0-cp313-cp313-manylinux_3_0_x86_64.whl", False),
            ("foo-1.0-cp313-cp313-musllinux_1_2_x86_64.whl", False),
            # wrong OS entirely: never a valid CentOS 7 runtime wheel
            ("foo-1.0-cp313-cp313-win_amd64.whl", False),
            ("foo-1.0-cp313-cp313-manylinux_2_28_x86_64.win_amd64.whl", False),
        ],
    )
    def test_wheel_compat_table(self, wheel: str, compatible: bool) -> None:
        assert (br.linux_abi_problems([wheel]) == []) is compatible

    def test_problems_name_the_offending_wheel(self) -> None:
        problems = br.linux_abi_problems(
            [
                "foo-1.0-py3-none-any.whl",
                "foo-1.0-cp313-cp313-linux_x86_64.whl",
                "foo-1.0-cp313-cp313-manylinux_2_28_x86_64.whl",
            ]
        )
        assert len(problems) == 2
        assert all("linux_x86_64" in p or "manylinux_2_28" in p for p in problems)

    def test_malformed_wheel_filename_reported(self) -> None:
        assert br.linux_abi_problems(["not-a-wheel.whl"]) != []

    def test_wheel_platform_tags(self) -> None:
        name = "foo-1.0-cp313-cp313-manylinux_2_28_x86_64.manylinux_2_17_x86_64.whl"
        assert br.wheel_platform_tags(name) == ["manylinux_2_28_x86_64", "manylinux_2_17_x86_64"]
        assert br.is_universal_wheel(name) is False
        assert br.is_universal_wheel("foo-1.0-py3-none-any.whl") is True

    def test_non_universal_platform_tags_reporting(self) -> None:
        tags = br.non_universal_platform_tags(
            [
                "foo-1.0-py3-none-any.whl",
                "foo-1.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
                "bar-2.0-cp313-cp313-manylinux2014_x86_64.whl",
            ]
        )
        assert tags == ["manylinux2014_x86_64", "manylinux_2_17_x86_64"]
